require "plugins"

require "core.options"
require "core.keymaps"
require "core.colorscheme"
require "core.highlights"

require "customs.impatient"
require "customs.autocommands"
require "customs.cmp"
require "customs.telescope"
require "customs.gitsigns"
require "customs.treesitter"
require "customs.autopairs"
require "customs.comment"
require "customs.nvim-tree"
require "customs.bufferline"
require "customs.lualine"
require "customs.toggleterm"
require "customs.project"
require "customs.illuminate"
require "customs.indentline"
require "customs.alpha"
require "customs.lsp"
require "customs.dap"
